spring:
  profiles:
    active:
    - dev
---
server:
  port: 8083
spring:
  profiles: dev    #开发环境
  application:
    name: mircoservicecloud-config-atguigu-dev
 
eureka:
   client:
      service-url:
         defaultZone: http:/eureka-test.com:7001/eureka/
---
spring:
  profiles: test   #测试环境
  application:
    name: mircoservicecloud-config-atguigu-test
#请保存为UTF-8格式
