spring:
  profiles:
  active:
  - dev
 ---
 server:
   port: 7001 #注册中心端口号

spring:
  profiles:dev
  application:
      name: mircoservicecloud-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url: http://eureka7001.com:7001/eureka/
---
 server:
   port: 7001 #注册中心端口号

spring:
  profiles:test
  application:
      name: mircoservicecloud-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url: http://eureka7001.com:7001/eureka/