spring:
  profiles:
    active:
    - dev
---
spring:
    port: 8201
spring:
  profiles: dev    #开发环境
  application:
    name: mircoservicecloud-client
eureka:
   client:
      service-url:
         defaultZonr: http:/eureka-dev.com:7001/eureka/
---
spring:
    port: 8202
spring:
  profiles: test    #测试环境
  application:
    name: mircoservicecloud-config-client
eureka:
   client:
      service-url:
         defaultZonr: http:/eureka-test.com:7001/eureka/