spring:
  profiles:
    active:
    - dev
---
  server:
    port: 7001 #注册中心端口号

spring:
  profiles: dev
  application:
    name: mircoservicecloud-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    enable-self-preservation: false #禁用eureka自我保护机制
---
server:
  port: 7001 #注册中心端口号

spring:
  profiles: test
  application:
    name: mircoservicecloud-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka/
  server:
    enable-self-preservation: false #禁用eureka自我保护机制
spring:
  profiles:
    active:
    - dev
---
server:
  port: 7001 #注册中心端口号

spring:
  profiles: dev
  application:
    name: mircoservicecloud-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    enable-self-preservation: false #禁用eureka自我保护机制
---
server:
  port: 7001 #注册中心端口号

spring:
  profiles: test
  application:
    name: mircoservicecloud-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    enable-self-preservation: false #禁用eureka自我保护机制
